### PR TITLE
Fix eye height textfield events / Show error if IGRF11.COF corrupt / Remember dialogs size & position / Add a new "Duplicate" button in SightsDialog / Other date&time fixes / Clock offset fixes

### PR DESCRIPTION
**Pull request by stelian42**

### CODE REVIEW

**Comment by rgleason** [comment]
Sean would you mind merging Stelian's PR? As we have tested it thoroughly!

**Comment by rgleason** [comment]
Thanks Stelian.

**Comment by stelian42** [comment]
Sean, if you're concerned about this pull request containing many (unrelated) fixes, I can understand this and maybe (just maybe because I don't have a lot of time at the moment) I can split the fixes in several merge branches.

Anyway, any kind of feedback would be appreciated.

**Comment by seandepagnier** [comment]
Sorry, I actually just missed this one somehow, I would have merged sooner.

**Comment by stelian42** [comment]
Thanks !

**Pull request merged**
